# Generated by Django 2.2 on 2019-04-21 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('username', models.CharField(default='yanjia666', max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wh_id', models.IntegerField()),
                ('w_x', models.IntegerField()),
                ('w_y', models.IntegerField()),
                ('d_x', models.IntegerField()),
                ('d_y', models.IntegerField()),
                ('loaded', models.BooleanField()),
                ('status', models.TextField(null=True)),
                ('acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.account')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.truck')),
            ],
        ),
    ]
