# Generated by Django 2.2 on 2019-04-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='delivered_t',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='delivering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='delivering_t',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='loading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='loading_t',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='waiting_t',
            field=models.TextField(null=True),
        ),
    ]
